-- Token codes for store-manager multi-factor login
-- One-time codes generated by a super admin per store-manager account.
create table if not exists public.admin_token_codes (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references public.admins(id) on delete cascade,
  code text not null,
  used_at timestamptz null,
  created_at timestamptz not null default now(),
  unique (admin_id, code)
);

create index if not exists admin_token_codes_admin_id_idx
  on public.admin_token_codes (admin_id);
create index if not exists admin_token_codes_code_idx
  on public.admin_token_codes (code);
